### ISSUE TITLE
psycopg2.errors.UndefinedFunction

### ISSUE THREAD

**Issue by annashutova** [siriusdevs/rpm_simple_http_server_7_1#3]
@siriusdevs 
https://github.com/siriusdevs/rpm_simple_http_server_7_1/blob/2ac3718125163b2a90a8dc79b0c33a645f4de5b7/db_utils.py#L27-L33

When trying to search for a student in the database and writing in, for example, "First name" field integer value like 200 server goes down and psycopg2 raises an error UndefinedFunction:
![Снимок экрана от 2023-03-22 17-53-46](https://user-images.githubusercontent.com/113082839/226944133-84a1c699-4595-4eac-839a-3adf2de02c59.png)

**We can correct this by simply adding `try except` for lines 28 and 29**

**Comment by siriusdevs** [comment]
@annashutova Thanks a lot!
You are welcome to create new issues in case you find more.
New collaborators swore to fix them all.

You can fix this issue yourself if you'd like! Just create a PR and link it to this ussue. If your commit will have words "fixes #3" (or [other words](https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request)) in its message, the issue will be closed with it automatically.

**Comment by siriusdevs** [comment]
ofc u can, just return/log error information explicitly
